#pragma once

#include <string>
#include <chrono>
#include <optional>
#include <memory>
#include "meld/kernel/primitives.hpp"

namespace meld {
namespace provenance {

// Import kernel::Value for convenience
using kernel::Value;

/**
 * OriginType - Classification of code origin for trust tracking
 * 
 * This enum defines the three fundamental categories of code origin
 * used throughout the Meld system for trust and safety analysis.
 */
enum class OriginType {
    Human,      // Code written directly by human developers
    Agent,      // Code generated by AI agents
    Verified    // Code that has been reviewed and verified by humans
};

/**
 * ProvenanceMetadata - Complete provenance information for AST nodes
 * 
 * This structure contains all metadata needed to track the origin,
 * authorship, and trust level of code elements in the Meld system.
 */
struct ProvenanceMetadata {
    // Core provenance fields
    OriginType origin;
    std::chrono::system_clock::time_point creation_timestamp;
    
    // Human-authored code fields
    std::optional<std::string> author_email;
    std::optional<std::string> commit_hash;
    
    // AI-generated code fields
    std::optional<std::string> agent_model;
    std::optional<double> confidence_score;  // 0.0 to 1.0
    std::optional<std::string> blueprint_id; // Link to @blueprint
    
    // Verification fields
    std::optional<std::string> reviewer_email;
    std::optional<std::chrono::system_clock::time_point> verification_timestamp;
    
    // Trust calculation
    double trust_score;  // Calculated based on origin and confidence
    
    // Default constructor for Human origin
    ProvenanceMetadata() 
        : origin(OriginType::Human)
        , creation_timestamp(std::chrono::system_clock::now())
        , trust_score(1.0) {}
    
    // Constructor for Agent origin
    ProvenanceMetadata(const std::string& model, double confidence, const std::string& blueprint = "")
        : origin(OriginType::Agent)
        , creation_timestamp(std::chrono::system_clock::now())
        , agent_model(model)
        , confidence_score(confidence)
        , blueprint_id(blueprint.empty() ? std::nullopt : std::make_optional(blueprint))
        , trust_score(confidence) {}
    
    // Constructor for Human origin with author
    ProvenanceMetadata(const std::string& author, const std::string& commit = "")
        : origin(OriginType::Human)
        , creation_timestamp(std::chrono::system_clock::now())
        , author_email(author)
        , commit_hash(commit.empty() ? std::nullopt : std::make_optional(commit))
        , trust_score(1.0) {}
};

/**
 * MismatchType - Types of provenance mismatches that can be detected
 */
enum class MismatchType {
    CodeChangedBlueprintStale,      // Code was modified but blueprint wasn't updated
    BlueprintChangedCodeStale,      // Blueprint was updated but code wasn't regenerated
    BothChanged,                    // Both code and blueprint changed independently
    HashMissing,                    // Required hashes are missing from metadata
    StaleAICode,                    // AI-generated code is too old and needs review
    TrustLevelMismatch,             // Code trust level doesn't match requirements
    VerificationExpired             // Verification has expired and needs renewal
};

/**
 * ProvenanceMismatchReport - Detailed analysis of provenance mismatches
 */
struct ProvenanceMismatchReport {
    Value node;                                    // The AST node being analyzed
    std::vector<MismatchType> mismatch_types;      // Types of mismatches detected
    std::optional<ProvenanceMetadata> metadata;    // Current provenance metadata
    
    // Content hashes
    std::string current_blueprint_hash;
    std::string stored_blueprint_hash;
    std::string current_code_hash;
    std::string stored_code_hash;
    
    // Timestamps
    std::chrono::system_clock::time_point analysis_time;
    std::optional<std::chrono::system_clock::time_point> last_code_change;
    std::optional<std::chrono::system_clock::time_point> last_blueprint_change;
    
    // Severity assessment
    enum class Severity { Info, Warning, Error, Critical } severity;
    
    // Human-readable description
    std::string description;
    
    ProvenanceMismatchReport(const Value& n) 
        : node(n), analysis_time(std::chrono::system_clock::now()), severity(Severity::Info) {}
};

/**
 * CompilerWarning - Structured compiler warning for provenance mismatches
 */
struct CompilerWarning {
    enum class Level { Info, Warning, Error } level;
    std::string code;           // Warning code (e.g., "PROV001")
    std::string message;        // Human-readable warning message
    std::string file_path;      // Source file path
    int line_number;           // Line number in source
    int column_number;         // Column number in source
    std::vector<std::string> suggestions; // Suggested fixes
    
    CompilerWarning(Level lvl, const std::string& cd, const std::string& msg)
        : level(lvl), code(cd), message(msg), line_number(0), column_number(0) {}
};

/**
 * ResolutionSuggestion - Suggested actions to resolve provenance mismatches
 */
struct ResolutionSuggestion {
    enum class ActionType { 
        UpdateBlueprint,        // Update the @blueprint annotation
        RegenerateCode,         // Regenerate code from blueprint
        MarkAsIntentional,      // Mark the deviation as intentional
        RequestVerification,    // Submit for human verification
        UpdateTrustLevel,       // Adjust trust level requirements
        RefreshTimestamp        // Update timestamps to current
    } action;
    
    std::string description;    // Human-readable description
    std::string command;        // CLI command to execute (if applicable)
    int priority;              // Priority (1=highest, 5=lowest)
    bool automated;            // Can be applied automatically
    
    ResolutionSuggestion(ActionType act, const std::string& desc, int prio = 3)
        : action(act), description(desc), priority(prio), automated(false) {}
};

/**
 * Provenance API - Functions for attaching and retrieving provenance metadata
 * 
 * These functions provide a high-level interface for working with provenance
 * metadata on AST nodes using the kernel meta_set/meta_get primitives.
 */
class Provenance {
public:
    // Attach provenance metadata to an AST node
    static Value attachProvenance(const Value& node, const ProvenanceMetadata& metadata);
    
    // Retrieve provenance metadata from an AST node
    static std::optional<ProvenanceMetadata> getProvenance(const Value& node);
    
    // Check if a node has provenance metadata
    static bool hasProvenance(const Value& node);
    
    // Mark code as verified by a reviewer
    static Value markAsVerified(const Value& node, const std::string& reviewer_email);
    
    // Calculate trust score based on origin and confidence
    static double calculateTrustScore(const ProvenanceMetadata& metadata);
    
    // Enhanced trust score calculation with custom parameters
    static double calculateTrustScore(const ProvenanceMetadata& metadata, 
                                    double time_decay_factor,
                                    int decay_threshold_days,
                                    int verification_expiry_days);
    
    // Check if trust score meets minimum threshold
    static bool meetsTrustThreshold(const ProvenanceMetadata& metadata, double min_trust_level);
    
    // Get trust level category for a given score
    static std::string getTrustLevelCategory(double trust_score);
    
    // Validate trust level threshold value
    static bool isValidTrustThreshold(double threshold);
    
    // Query nodes by origin type
    static std::vector<Value> queryByOrigin(const std::vector<Value>& nodes, OriginType origin);
    
    // Query nodes by minimum trust level
    static std::vector<Value> queryByTrustLevel(const std::vector<Value>& nodes, double min_trust);
    
    // Comprehensive provenance query API with filtering support
    struct QueryFilter {
        std::optional<OriginType> origin_type;
        std::optional<double> min_confidence;
        std::optional<double> max_confidence;
        std::optional<double> min_trust_level;
        std::optional<std::string> agent_model;
        std::optional<std::string> author_email;
        std::optional<bool> verified_only;
        
        QueryFilter() = default;
        
        // Builder methods for fluent API
        QueryFilter& withOrigin(OriginType origin) { origin_type = origin; return *this; }
        QueryFilter& withMinConfidence(double confidence) { min_confidence = confidence; return *this; }
        QueryFilter& withMaxConfidence(double confidence) { max_confidence = confidence; return *this; }
        QueryFilter& withMinTrustLevel(double trust) { min_trust_level = trust; return *this; }
        QueryFilter& withAgentModel(const std::string& model) { agent_model = model; return *this; }
        QueryFilter& withAuthor(const std::string& author) { author_email = author; return *this; }
        QueryFilter& verifiedOnly() { verified_only = true; return *this; }
    };
    
    // Main query API - filters a collection of nodes based on provenance criteria
    static std::vector<Value> query(const std::vector<Value>& nodes, const QueryFilter& filter);
    
    // Convenience overload for single node inspection
    static bool matchesQuery(const Value& node, const QueryFilter& filter);
    
    // Detect provenance mismatches (code changed but blueprint didn't, etc.)
    static std::vector<std::string> detectMismatches(const Value& node, const std::string& current_blueprint);
    
    // Enhanced mismatch detection with detailed analysis
    static ProvenanceMismatchReport analyzeProvenance(const Value& node, const std::string& current_blueprint, const std::string& current_code);
    
    // Generate compiler warnings for mismatches
    static std::vector<CompilerWarning> generateMismatchWarnings(const ProvenanceMismatchReport& report);
    
    // Provide suggestions for resolving mismatches
    static std::vector<ResolutionSuggestion> suggestResolutions(const ProvenanceMismatchReport& report);
    
    // Hash functions for content comparison
    static std::string hashContent(const std::string& content);
    static std::string hashBlueprint(const std::string& blueprint);
    static std::string hashCode(const std::string& code);
    
    // Store content hashes for mismatch detection
    static Value attachContentHashes(const Value& node, const std::string& blueprint, const std::string& code);
    
    // Check if content has changed since last hash
    static bool hasContentChanged(const Value& node, const std::string& current_content, const std::string& hash_key);
    
private:
    // Internal helper to serialize metadata to Value
    static Value serializeMetadata(const ProvenanceMetadata& metadata);
    
    // Internal helper to deserialize metadata from Value
    static std::optional<ProvenanceMetadata> deserializeMetadata(const Value& value);
    
    // Constants for metadata keys
    static constexpr const char* PROVENANCE_KEY = "provenance";
    static constexpr const char* BLUEPRINT_HASH_KEY = "blueprint_hash";
    static constexpr const char* CODE_HASH_KEY = "code_hash";
};

/**
 * Trust Level Thresholds - Standard trust levels for compiler enforcement
 */
namespace TrustLevels {
    constexpr double VERIFIED = 1.0;        // Human-verified code
    constexpr double HIGH_CONFIDENCE = 0.9; // High-confidence AI code
    constexpr double MEDIUM_CONFIDENCE = 0.7; // Medium-confidence AI code
    constexpr double LOW_CONFIDENCE = 0.5;  // Low-confidence AI code
    constexpr double UNTRUSTED = 0.0;       // Untrusted or unknown code
}

/**
 * IDE Integration - Color coding for trust heatmap visualization
 */
namespace IDEColors {
    struct TrustColor {
        int red, green, blue, alpha;
        
        TrustColor(int r, int g, int b, int a = 255) : red(r), green(g), blue(b), alpha(a) {}
    };
    
    // Color scheme for trust visualization
    const TrustColor HUMAN_VERIFIED(0, 255, 0, 100);      // Green tint
    const TrustColor HIGH_CONFIDENCE_AGENT(128, 0, 255, 80); // Purple tint
    const TrustColor MEDIUM_CONFIDENCE_AGENT(255, 165, 0, 80); // Orange tint
    const TrustColor LOW_CONFIDENCE_AGENT(255, 0, 0, 100);  // Red tint
    
    // Get color for trust score
    TrustColor getColorForTrust(double trust_score);
    
    // Get gutter icon for origin type
    std::string getGutterIcon(OriginType origin);
}

/**
 * TrustLevelEnforcer - Compiler integration for trust level enforcement
 */
class TrustLevelEnforcer {
public:
    // Constructor with minimum trust level
    explicit TrustLevelEnforcer(double min_trust_level);
    
    // Check if a node meets the minimum trust requirement
    bool checkNode(const Value& node) const;
    
    // Check multiple nodes and return violations
    std::vector<Value> findViolations(const std::vector<Value>& nodes) const;
    
    // Generate compiler errors for trust violations
    std::vector<CompilerWarning> generateTrustViolationWarnings(const std::vector<Value>& violations) const;
    
    // Get the current minimum trust level
    double getMinimumTrustLevel() const { return min_trust_level_; }
    
    // Set a new minimum trust level
    void setMinimumTrustLevel(double min_trust_level);
    
    // Get statistics about trust levels in a set of nodes
    struct TrustStats {
        int total_nodes;
        int verified_nodes;
        int high_confidence_nodes;
        int medium_confidence_nodes;
        int low_confidence_nodes;
        int untrusted_nodes;
        int violations;
        double average_trust_score;
        double minimum_trust_score;
        double maximum_trust_score;
    };
    
    TrustStats analyzeTrustLevels(const std::vector<Value>& nodes) const;
    
private:
    double min_trust_level_;
    
    // Helper to get trust score for a node
    double getNodeTrustScore(const Value& node) const;
};

} // namespace provenance
} // namespace meld