#include "meld/history/ide_integration.hpp"
#include <sstream>
#include <iomanip>
#include <ctime>

namespace meld {
namespace history {

IDEIntegration::IDEIntegration(HistoryAPI& historyAPI)
    : historyAPI_(historyAPI) {}

Color IDEIntegration::getGutterColor(const std::string& nodeId) {
    auto history = historyAPI_.queryByNodeId(nodeId);
    if (!history) {
        return Color::Gray();  // No history
    }
    
    int versionCount = history->getVersionCount();
    
    if (versionCount == 0) {
        return Color::Green();      // Original code
    } else if (versionCount <= 2) {
        return Color::Yellow();     // Few iterations
    } else if (versionCount <= 5) {
        return Color::Orange();     // Several iterations
    } else {
        return Color::Red();        // Many iterations (potential issue)
    }
}

std::string IDEIntegration::formatTimestamp(const Timestamp& ts) {
    auto time = std::chrono::system_clock::to_time_t(ts);
    std::stringstream ss;
    ss << std::put_time(std::localtime(&time), "%Y-%m-%d %H:%M:%S");
    return ss.str();
}

std::string IDEIntegration::getHistoryTooltip(const std::string& nodeId) {
    auto history = historyAPI_.queryByNodeId(nodeId);
    if (!history) {
        return "No history available";
    }
    
    std::ostringstream tooltip;
    tooltip << "Generated by: " << history->agentModel << "\n";
    tooltip << "Versions: " << history->getVersionCount() << "\n";
    tooltip << "Last updated: " << formatTimestamp(history->updatedAt) << "\n";
    
    if (!history->conversation.empty()) {
        tooltip << "Conversation messages: " << history->conversation.size() << "\n";
    }
    
    tooltip << "\nClick to view full conversation history";
    
    return tooltip.str();
}

std::string IDEIntegration::formatMessage(const Message& msg) {
    std::ostringstream formatted;
    formatted << "[" << formatTimestamp(msg.timestamp) << "] ";
    formatted << msg.role << ": ";
    
    // Truncate long messages for display
    if (msg.content.length() > 200) {
        formatted << msg.content.substr(0, 197) << "...";
    } else {
        formatted << msg.content;
    }
    
    return formatted.str();
}

std::string IDEIntegration::formatVersion(const CodeVersion& version) {
    std::ostringstream formatted;
    formatted << "Version " << version.versionNumber << " - ";
    formatted << formatTimestamp(version.timestamp) << "\n";
    formatted << "Reason: " << version.changeReason << "\n";
    formatted << "---\n";
    formatted << version.code << "\n";
    
    return formatted.str();
}

std::string IDEIntegration::getHistoryPanel(const std::string& nodeId) {
    auto history = historyAPI_.queryByNodeId(nodeId);
    if (!history) {
        return "No history available for this node.";
    }
    
    std::ostringstream panel;
    
    // Header
    panel << "=== History for " << history->functionName << " ===\n\n";
    panel << "Node ID: " << history->nodeId << "\n";
    panel << "File: " << history->filePath << "\n";
    panel << "Agent Model: " << history->agentModel << "\n";
    panel << "Created: " << formatTimestamp(history->createdAt) << "\n";
    panel << "Last Updated: " << formatTimestamp(history->updatedAt) << "\n";
    panel << "Total Versions: " << history->getVersionCount() << "\n\n";
    
    // Conversation section
    if (!history->conversation.empty()) {
        panel << "--- Conversation ---\n\n";
        for (const auto& msg : history->conversation) {
            panel << formatMessage(msg) << "\n\n";
        }
    }
    
    // Version history section
    if (!history->versions.empty()) {
        panel << "--- Version History ---\n\n";
        for (const auto& version : history->versions) {
            panel << formatVersion(version) << "\n";
        }
    }
    
    // Blueprint history section
    if (history->originalBlueprint || history->currentBlueprint) {
        panel << "--- Blueprint Evolution ---\n\n";
        if (history->originalBlueprint) {
            panel << "Original Blueprint:\n" << *history->originalBlueprint << "\n\n";
        }
        if (history->currentBlueprint) {
            panel << "Current Blueprint:\n" << *history->currentBlueprint << "\n\n";
        }
    }
    
    return panel.str();
}

std::string IDEIntegration::getVersionTimeline(const std::string& nodeId) {
    auto history = historyAPI_.queryByNodeId(nodeId);
    if (!history) {
        return "No version history available.";
    }
    
    std::ostringstream timeline;
    timeline << "=== Version Timeline for " << history->functionName << " ===\n\n";
    
    if (history->versions.empty()) {
        timeline << "Original version (no changes)\n";
        timeline << "Created: " << formatTimestamp(history->createdAt) << "\n";
    } else {
        // Show creation
        timeline << "v0 (Original) - " << formatTimestamp(history->createdAt) << "\n";
        timeline << "  └─ Initial creation\n\n";
        
        // Show each version
        for (const auto& version : history->versions) {
            timeline << "v" << version.versionNumber << " - ";
            timeline << formatTimestamp(version.timestamp) << "\n";
            timeline << "  └─ " << version.changeReason << "\n\n";
        }
    }
    
    return timeline.str();
}

std::string IDEIntegration::getConversationView(const std::string& nodeId) {
    auto history = historyAPI_.queryByNodeId(nodeId);
    if (!history) {
        return "No conversation history available.";
    }
    
    if (history->conversation.empty()) {
        return "No conversation recorded for this function.";
    }
    
    std::ostringstream view;
    view << "=== Conversation for " << history->functionName << " ===\n\n";
    view << "Agent Model: " << history->agentModel << "\n\n";
    
    for (const auto& msg : history->conversation) {
        view << "┌─ " << msg.role << " [" << formatTimestamp(msg.timestamp) << "]\n";
        view << "│\n";
        
        // Split content into lines for better formatting
        std::istringstream contentStream(msg.content);
        std::string line;
        while (std::getline(contentStream, line)) {
            view << "│  " << line << "\n";
        }
        
        view << "└─\n\n";
    }
    
    return view.str();
}

float IDEIntegration::getTrustIntensity(const std::string& nodeId) {
    auto history = historyAPI_.queryByNodeId(nodeId);
    if (!history) {
        return 0.5f;  // Neutral for unknown
    }
    
    int versionCount = history->getVersionCount();
    
    // More versions = less trust (more iterations needed)
    if (versionCount == 0) {
        return 1.0f;  // Original, high trust
    } else if (versionCount <= 2) {
        return 0.8f;  // Few iterations, good trust
    } else if (versionCount <= 5) {
        return 0.5f;  // Several iterations, moderate trust
    } else {
        return 0.2f;  // Many iterations, low trust
    }
}

std::string IDEIntegration::getHistorySummary(const std::string& nodeId) {
    auto history = historyAPI_.queryByNodeId(nodeId);
    if (!history) {
        return "No history";
    }
    
    std::ostringstream summary;
    summary << history->agentModel << " | ";
    summary << history->getVersionCount() << " versions | ";
    summary << history->conversation.size() << " messages";
    
    return summary.str();
}

} // namespace history
} // namespace meld
