#include "meld/history/source_validator.hpp"
#include <fstream>
#include <sstream>
#include <algorithm>

namespace meld {
namespace history {

std::string SourceValidator::trim(const std::string& str) {
    auto start = str.find_first_not_of(" \t\r\n");
    if (start == std::string::npos) return "";
    
    auto end = str.find_last_not_of(" \t\r\n");
    return str.substr(start, end - start + 1);
}

bool SourceValidator::matchesPattern(const std::string& line, const std::string& pattern) {
    std::string trimmedLine = trim(line);
    return trimmedLine.find(pattern) != std::string::npos;
}

bool SourceValidator::containsInlineHistory(const std::string& line) {
    for (const auto& pattern : forbiddenPatterns_) {
        if (matchesPattern(line, pattern)) {
            return true;
        }
    }
    return false;
}

bool SourceValidator::containsGenerationComment(const std::string& line) {
    std::string trimmedLine = trim(line);
    return trimmedLine.find("// AI Generated:") != std::string::npos ||
           trimmedLine.find("// Generated by:") != std::string::npos ||
           trimmedLine.find("/* AI Generated") != std::string::npos ||
           trimmedLine.find("/* Generated by") != std::string::npos;
}

bool SourceValidator::containsConversationMarker(const std::string& line) {
    std::string trimmedLine = trim(line);
    return trimmedLine.find("// Conversation:") != std::string::npos ||
           trimmedLine.find("// User:") != std::string::npos ||
           trimmedLine.find("// Assistant:") != std::string::npos ||
           trimmedLine.find("/* Conversation") != std::string::npos;
}

std::vector<std::string> SourceValidator::getForbiddenPatterns() {
    return forbiddenPatterns_;
}

ValidationResult SourceValidator::validateFile(const std::filesystem::path& filePath) {
    ValidationResult result;
    
    // Check if file exists
    if (!std::filesystem::exists(filePath)) {
        result.addViolation("File does not exist: " + filePath.string());
        return result;
    }
    
    // Check if it's a source file
    std::string extension = filePath.extension().string();
    if (extension != ".meld" && extension != ".cpp" && extension != ".hpp" && 
        extension != ".h" && extension != ".c") {
        // Not a source file, skip validation
        return result;
    }
    
    // Read file
    std::ifstream file(filePath);
    if (!file.is_open()) {
        result.addViolation("Cannot open file: " + filePath.string());
        return result;
    }
    
    std::string line;
    int lineNumber = 0;
    
    while (std::getline(file, line)) {
        lineNumber++;
        
        // Check for inline history
        if (containsInlineHistory(line)) {
            std::ostringstream violation;
            violation << filePath.string() << ":" << lineNumber 
                     << " - Contains inline history: " << trim(line);
            result.addViolation(violation.str());
        }
        
        // Check for generation comments
        if (containsGenerationComment(line)) {
            std::ostringstream violation;
            violation << filePath.string() << ":" << lineNumber 
                     << " - Contains generation comment: " << trim(line);
            result.addViolation(violation.str());
        }
        
        // Check for conversation markers
        if (containsConversationMarker(line)) {
            std::ostringstream violation;
            violation << filePath.string() << ":" << lineNumber 
                     << " - Contains conversation marker: " << trim(line);
            result.addViolation(violation.str());
        }
    }
    
    file.close();
    
    // Add warning if file is clean
    if (result.isValid) {
        result.addWarning("File is clean: " + filePath.string());
    }
    
    return result;
}

ValidationResult SourceValidator::validateDirectory(const std::filesystem::path& dirPath) {
    ValidationResult result;
    
    // Check if directory exists
    if (!std::filesystem::exists(dirPath)) {
        result.addViolation("Directory does not exist: " + dirPath.string());
        return result;
    }
    
    if (!std::filesystem::is_directory(dirPath)) {
        result.addViolation("Path is not a directory: " + dirPath.string());
        return result;
    }
    
    // Recursively validate all source files
    for (const auto& entry : std::filesystem::recursive_directory_iterator(dirPath)) {
        if (entry.is_regular_file()) {
            std::string extension = entry.path().extension().string();
            
            // Only validate source files
            if (extension == ".meld" || extension == ".cpp" || extension == ".hpp" || 
                extension == ".h" || extension == ".c") {
                
                ValidationResult fileResult = validateFile(entry.path());
                
                // Merge results
                for (const auto& violation : fileResult.violations) {
                    result.addViolation(violation);
                }
                
                for (const auto& warning : fileResult.warnings) {
                    result.addWarning(warning);
                }
            }
        }
    }
    
    return result;
}

} // namespace history
} // namespace meld
