#include "meld/compiler/codegen.hpp"
#include "meld/compiler/jvm_backend.hpp"
#include <sstream>
#include <algorithm>

namespace meld::compiler {

CodeGenerator::CodeGenerator(CodeGenTarget target)
    : target_(target) {
}

std::string CodeGenerator::generate(const ir::Module& module) {
    switch (target_) {
        case CodeGenTarget::CPP:
            return generate_cpp(module);
        case CodeGenTarget::JVM:
            return generate_jvm(module);
        case CodeGenTarget::Go:
            return generate_go(module);
        case CodeGenTarget::LLVM_IR:
            return "LLVM IR generation not yet implemented";
        case CodeGenTarget::Bytecode:
            return "Bytecode generation not yet implemented";
        case CodeGenTarget::JavaScript:
            return "JavaScript generation not yet implemented";
        default:
            return "Unknown target";
    }
}

std::string CodeGenerator::generate_function(const ir::Function& function) {
    if (target_ == CodeGenTarget::CPP) {
        return generate_cpp_function(function);
    }
    return "";
}

std::string CodeGenerator::generate_block(const ir::BasicBlock& block) {
    std::ostringstream oss;
    
    // Generate label
    oss << block.label << ":" << std::endl;
    
    // Generate instructions
    for (const auto& inst : block.instructions) {
        oss << "  " << generate_instruction(*inst) << std::endl;
    }
    
    return oss.str();
}

std::string CodeGenerator::generate_instruction(const ir::Instruction& inst) {
    if (target_ == CodeGenTarget::CPP) {
        return generate_cpp_instruction(inst);
    }
    return inst.to_string();
}

void CodeGenerator::set_optimization_level(int level) {
    optimization_level_ = std::clamp(level, 0, 3);
}

void CodeGenerator::set_debug_info(bool enabled) {
    debug_info_ = enabled;
}

// C++ code generation
std::string CodeGenerator::generate_cpp(const ir::Module& module) {
    std::ostringstream oss;
    
    // Header
    oss << "// Generated by Meld Compiler" << std::endl;
    oss << "#include <cstdint>" << std::endl;
    oss << "#include <string>" << std::endl;
    oss << "#include <iostream>" << std::endl;
    oss << std::endl;
    
    // Namespace
    oss << "namespace meld_generated {" << std::endl << std::endl;
    
    // Global variables
    if (!module.globals.empty()) {
        oss << "// Global variables" << std::endl;
        for (const auto& global : module.globals) {
            oss << cpp_type_name(global->type) << " " << cpp_value_name(*global) << ";" << std::endl;
        }
        oss << std::endl;
    }
    
    // Functions
    for (const auto& func : module.functions) {
        oss << generate_cpp_function(*func) << std::endl;
    }
    
    oss << "} // namespace meld_generated" << std::endl;
    
    return oss.str();
}

// Go code generation
std::string CodeGenerator::generate_go(const ir::Module& module) {
    std::ostringstream oss;
    
    // Header
    oss << "// Generated by Meld Compiler" << std::endl;
    oss << "package main" << std::endl;
    oss << std::endl;
    oss << "import (" << std::endl;
    oss << "    \"fmt\"" << std::endl;
    oss << ")" << std::endl;
    oss << std::endl;
    
    // Global variables
    if (!module.globals.empty()) {
        oss << "// Global variables" << std::endl;
        for (const auto& global : module.globals) {
            std::string go_type = "interface{}"; // Default fallback
            if (global->meta_type) {
                go_type = get_native_type_name(global->meta_type->name(), CodeGenTarget::Go);
            }
            oss << "var " << cpp_value_name(*global) << " " << go_type << std::endl;
        }
        oss << std::endl;
    }
    
    // Functions
    for (const auto& func : module.functions) {
        oss << generate_go_function(*func) << std::endl;
    }
    
    return oss.str();
}

std::string CodeGenerator::generate_go_function(const ir::Function& function) {
    std::ostringstream oss;
    
    // Function signature
    oss << "func " << mangle_name(function.name) << "(";
    for (size_t i = 0; i < function.parameters.size(); ++i) {
        if (i > 0) oss << ", ";
        const auto& param = function.parameters[i];
        std::string go_type = "interface{}"; // Default fallback
        if (param->meta_type) {
            go_type = get_native_type_name(param->meta_type->name(), CodeGenTarget::Go);
        }
        oss << cpp_value_name(*param) << " " << go_type;
    }
    oss << ")";
    
    // Return type
    if (function.return_value && function.return_value->meta_type) {
        oss << " " << get_native_type_name(function.return_value->meta_type->name(), CodeGenTarget::Go);
    }
    
    oss << " {" << std::endl;
    
    // Function body - basic implementation
    oss << "    // Function body not yet implemented" << std::endl;
    
    oss << "}" << std::endl;
    
    return oss.str();
}
std::string CodeGenerator::generate_jvm(const ir::Module& module) {
    JVMGenerationOptions jvm_options;
    jvm_options.package_name = "meld.generated";
    jvm_options.use_modern_java = true;
    jvm_options.java_version = 17;
    jvm_options.include_debug_info = debug_info_;
    
    JVMBackend jvm_backend(jvm_options);
    auto java_files = jvm_backend.generate_java_files(module);
    
    // For now, return the main class content
    // In a full implementation, this would write multiple files
    std::ostringstream oss;
    oss << "// Generated Java files:" << std::endl;
    for (const auto& [filename, content] : java_files) {
        oss << "// File: " << filename << std::endl;
        oss << content << std::endl << std::endl;
    }
    
    return oss.str();
}

std::string CodeGenerator::generate_cpp_function(const ir::Function& function) {
    std::ostringstream oss;
    
    // Function signature
    oss << "auto " << mangle_name(function.name) << "(";
    for (size_t i = 0; i < function.parameters.size(); ++i) {
        if (i > 0) oss << ", ";
        const auto& param = function.parameters[i];
        oss << cpp_type_name(param->type) << " " << cpp_value_name(*param);
    }
    oss << ")";
    
    // Return type
    if (function.return_value) {
        oss << " -> " << cpp_type_name(function.return_value->type);
    } else {
        oss << " -> void";
    }
    
    oss << " {" << std::endl;
    
    // Function body - generate code for each basic block
    for (const auto& block : function.basic_blocks) {
        // Skip label for entry block
        if (block != function.basic_blocks.front()) {
            oss << "  " << block->label << ":" << std::endl;
        }
        
        // Generate instructions
        for (const auto& inst : block->instructions) {
            std::string inst_code = generate_cpp_instruction(*inst);
            if (!inst_code.empty()) {
                oss << "  " << inst_code << ";" << std::endl;
            }
        }
    }
    
    oss << "}" << std::endl;
    
    return oss.str();
}

std::string CodeGenerator::generate_cpp_instruction(const ir::Instruction& inst) {
    std::ostringstream oss;
    
    switch (inst.opcode) {
        // Arithmetic
        case ir::Opcode::Add:
            oss << cpp_type_name(inst.result->type) << " " << cpp_value_name(*inst.result)
                << " = " << cpp_value_name(*inst.operands[0])
                << " + " << cpp_value_name(*inst.operands[1]);
            break;
            
        case ir::Opcode::Sub:
            oss << cpp_type_name(inst.result->type) << " " << cpp_value_name(*inst.result)
                << " = " << cpp_value_name(*inst.operands[0])
                << " - " << cpp_value_name(*inst.operands[1]);
            break;
            
        case ir::Opcode::Mul:
            oss << cpp_type_name(inst.result->type) << " " << cpp_value_name(*inst.result)
                << " = " << cpp_value_name(*inst.operands[0])
                << " * " << cpp_value_name(*inst.operands[1]);
            break;
            
        case ir::Opcode::Div:
            oss << cpp_type_name(inst.result->type) << " " << cpp_value_name(*inst.result)
                << " = " << cpp_value_name(*inst.operands[0])
                << " / " << cpp_value_name(*inst.operands[1]);
            break;
            
        case ir::Opcode::Neg:
            oss << cpp_type_name(inst.result->type) << " " << cpp_value_name(*inst.result)
                << " = -" << cpp_value_name(*inst.operands[0]);
            break;
            
        // Logical
        case ir::Opcode::And:
            oss << cpp_type_name(inst.result->type) << " " << cpp_value_name(*inst.result)
                << " = " << cpp_value_name(*inst.operands[0])
                << " && " << cpp_value_name(*inst.operands[1]);
            break;
            
        case ir::Opcode::Or:
            oss << cpp_type_name(inst.result->type) << " " << cpp_value_name(*inst.result)
                << " = " << cpp_value_name(*inst.operands[0])
                << " || " << cpp_value_name(*inst.operands[1]);
            break;
            
        case ir::Opcode::Not:
            oss << cpp_type_name(inst.result->type) << " " << cpp_value_name(*inst.result)
                << " = !" << cpp_value_name(*inst.operands[0]);
            break;
            
        // Comparison
        case ir::Opcode::Eq:
            oss << cpp_type_name(inst.result->type) << " " << cpp_value_name(*inst.result)
                << " = " << cpp_value_name(*inst.operands[0])
                << " == " << cpp_value_name(*inst.operands[1]);
            break;
            
        case ir::Opcode::Ne:
            oss << cpp_type_name(inst.result->type) << " " << cpp_value_name(*inst.result)
                << " = " << cpp_value_name(*inst.operands[0])
                << " != " << cpp_value_name(*inst.operands[1]);
            break;
            
        case ir::Opcode::Lt:
            oss << cpp_type_name(inst.result->type) << " " << cpp_value_name(*inst.result)
                << " = " << cpp_value_name(*inst.operands[0])
                << " < " << cpp_value_name(*inst.operands[1]);
            break;
            
        case ir::Opcode::Le:
            oss << cpp_type_name(inst.result->type) << " " << cpp_value_name(*inst.result)
                << " = " << cpp_value_name(*inst.operands[0])
                << " <= " << cpp_value_name(*inst.operands[1]);
            break;
            
        case ir::Opcode::Gt:
            oss << cpp_type_name(inst.result->type) << " " << cpp_value_name(*inst.result)
                << " = " << cpp_value_name(*inst.operands[0])
                << " > " << cpp_value_name(*inst.operands[1]);
            break;
            
        case ir::Opcode::Ge:
            oss << cpp_type_name(inst.result->type) << " " << cpp_value_name(*inst.result)
                << " = " << cpp_value_name(*inst.operands[0])
                << " >= " << cpp_value_name(*inst.operands[1]);
            break;
            
        // Memory
        case ir::Opcode::Alloca:
            oss << cpp_type_name(inst.result->type) << " " << cpp_value_name(*inst.result);
            break;
            
        case ir::Opcode::Load:
            oss << cpp_type_name(inst.result->type) << " " << cpp_value_name(*inst.result)
                << " = " << cpp_value_name(*inst.operands[0]);
            break;
            
        case ir::Opcode::Store:
            oss << cpp_value_name(*inst.operands[1])
                << " = " << cpp_value_name(*inst.operands[0]);
            break;
            
        // Control flow
        case ir::Opcode::Return:
            if (!inst.operands.empty()) {
                oss << "return " << cpp_value_name(*inst.operands[0]);
            } else {
                oss << "return";
            }
            break;
            
        case ir::Opcode::Branch:
            oss << "goto " << inst.target_label;
            break;
            
        case ir::Opcode::CondBranch:
            oss << "if (" << cpp_value_name(*inst.operands[0]) << ") goto " << inst.target_label
                << "; else goto " << inst.else_label;
            break;
            
        case ir::Opcode::Call:
            if (inst.result) {
                oss << cpp_type_name(inst.result->type) << " " << cpp_value_name(*inst.result) << " = ";
            }
            oss << cpp_value_name(*inst.operands[0]) << "(";
            for (size_t i = 1; i < inst.operands.size(); ++i) {
                if (i > 1) oss << ", ";
                oss << cpp_value_name(*inst.operands[i]);
            }
            oss << ")";
            break;
            
        // Constants
        case ir::Opcode::ConstInt:
            oss << cpp_type_name(inst.result->type) << " " << cpp_value_name(*inst.result)
                << " = " << std::get<int64_t>(inst.constant_value);
            break;
            
        case ir::Opcode::ConstBool:
            oss << cpp_type_name(inst.result->type) << " " << cpp_value_name(*inst.result)
                << " = " << (std::get<bool>(inst.constant_value) ? "true" : "false");
            break;
            
        case ir::Opcode::ConstString:
            oss << cpp_type_name(inst.result->type) << " " << cpp_value_name(*inst.result)
                << " = \"" << std::get<std::string>(inst.constant_value) << "\"";
            break;
            
        case ir::Opcode::ConstNull:
            oss << cpp_type_name(inst.result->type) << " " << cpp_value_name(*inst.result)
                << " = nullptr";
            break;
            
        default:
            oss << "/* Unsupported opcode */";
            break;
    }
    
    return oss.str();
}

std::string CodeGenerator::cpp_type_name(ir::ValueType type) {
    switch (type) {
        case ir::ValueType::Void: return "void";
        case ir::ValueType::Int: return "int64_t";
        case ir::ValueType::Float: return "double";
        case ir::ValueType::Bool: return "bool";
        case ir::ValueType::String: return "std::string";
        case ir::ValueType::Pointer: return "void*";
        case ir::ValueType::Struct: return "struct";
        case ir::ValueType::Function: return "auto";
        default: return "void";
    }
}

std::string CodeGenerator::cpp_type_name(const std::string& type_name) {
    // Use transpiler mappings for Meld type names
    return get_native_type_name(type_name, target_);
}

std::string CodeGenerator::cpp_value_name(const ir::Value& value) {
    // Clean up the name for C++
    std::string name = value.name;
    std::replace(name.begin(), name.end(), '%', '_');
    std::replace(name.begin(), name.end(), '.', '_');
    return name;
}

std::string CodeGenerator::mangle_name(const std::string& name) {
    // Simple name mangling - just prefix with meld_
    return "meld_" + name;
}

std::string CodeGenerator::get_native_type_name(const std::string& meld_type_name, CodeGenTarget target) {
    // Get the type from the registry
    auto& registry = meta::TypeRegistry::instance();
    auto type_result = registry.get_type(meld_type_name);
    
    if (!type_result.has_value()) {
        // Fallback to default mapping
        return cpp_type_name_fallback(meld_type_name);
    }
    
    return map_transpiler_annotation(type_result.value(), target);
}

std::string CodeGenerator::map_transpiler_annotation(const std::shared_ptr<meta::MetaType>& type, CodeGenTarget target) {
    if (!type->has_annotation("transpile_as")) {
        // No transpiler annotation, use default mapping
        return get_default_type_mapping(type->name(), target);
    }
    
    auto annotation_result = type->get_annotation("transpile_as");
    if (!annotation_result.has_value()) {
        return get_default_type_mapping(type->name(), target);
    }
    
    const auto& mappings = annotation_result.value();
    
    // Map target to annotation key
    std::string target_key;
    switch (target) {
        case CodeGenTarget::CPP:
            target_key = "cpp";
            break;
        case CodeGenTarget::JVM:
            target_key = "java";
            break;
        case CodeGenTarget::JavaScript:
            target_key = "js";
            break;
        case CodeGenTarget::Go:
            target_key = "go";
            break;
        default:
            return get_default_type_mapping(type->name(), target);
    }
    
    // Look up the mapping for this target
    auto it = mappings.find(target_key);
    if (it != mappings.end()) {
        return it->second;
    }
    
    // Fallback to default mapping if no specific mapping found
    return get_default_type_mapping(type->name(), target);
}

std::string CodeGenerator::get_default_type_mapping(const std::string& type_name, CodeGenTarget target) {
    switch (target) {
        case CodeGenTarget::CPP:
            return cpp_type_name_fallback(type_name);
        case CodeGenTarget::JVM:
            return java_type_name_fallback(type_name);
        case CodeGenTarget::JavaScript:
            return js_type_name_fallback(type_name);
        case CodeGenTarget::Go:
            return go_type_name_fallback(type_name);
        default:
            return type_name;
    }
}

std::string CodeGenerator::java_type_name_fallback(const std::string& type_name) {
    // Fallback mappings for Java
    if (type_name == "int" || type_name == "Int") return "long";
    if (type_name == "float" || type_name == "Float") return "double";
    if (type_name == "bool" || type_name == "Bool") return "boolean";
    if (type_name == "string" || type_name == "String") return "String";
    if (type_name == "void" || type_name == "Void") return "void";
    
    // For unknown types, return as-is
    return type_name;
}

std::string CodeGenerator::js_type_name_fallback(const std::string& type_name) {
    // JavaScript is dynamically typed, but we can provide hints
    if (type_name == "int" || type_name == "Int") return "number";
    if (type_name == "float" || type_name == "Float") return "number";
    if (type_name == "bool" || type_name == "Bool") return "boolean";
    if (type_name == "string" || type_name == "String") return "string";
    if (type_name == "void" || type_name == "Void") return "void";
    
    // For unknown types, return as-is
    return type_name;
}

std::string CodeGenerator::go_type_name_fallback(const std::string& type_name) {
    // Fallback mappings for Go
    if (type_name == "int" || type_name == "Int") return "int64";
    if (type_name == "float" || type_name == "Float") return "float64";
    if (type_name == "bool" || type_name == "Bool") return "bool";
    if (type_name == "string" || type_name == "String") return "string";
    if (type_name == "void" || type_name == "Void") return "";  // Go uses empty for void
    
    // For unknown types, return as-is
    return type_name;
}

std::string CodeGenerator::cpp_type_name_fallback(const std::string& type_name) {
    // Fallback mappings for types without @transpile_as annotations
    if (type_name == "int" || type_name == "Int") return "int64_t";
    if (type_name == "float" || type_name == "Float") return "double";
    if (type_name == "bool" || type_name == "Bool") return "bool";
    if (type_name == "string" || type_name == "String") return "std::string";
    if (type_name == "void" || type_name == "Void") return "void";
    
    // For unknown types, return as-is
    return type_name;
}

// RuntimeLinker implementation
std::string RuntimeLinker::link_runtime(const std::string& generated_code) {
    std::ostringstream oss;
    
    oss << get_runtime_header() << std::endl;
    oss << generated_code << std::endl;
    oss << get_runtime_impl() << std::endl;
    
    return oss.str();
}

std::string RuntimeLinker::get_runtime_header() {
    std::ostringstream oss;
    
    oss << "// Meld Runtime Library Header" << std::endl;
    oss << "#pragma once" << std::endl;
    oss << std::endl;
    oss << "#include <memory>" << std::endl;
    oss << "#include <string>" << std::endl;
    oss << "#include <vector>" << std::endl;
    oss << "#include <map>" << std::endl;
    oss << std::endl;
    oss << "namespace meld::runtime {" << std::endl;
    oss << std::endl;
    
    oss << generate_memory_management() << std::endl;
    oss << generate_type_system() << std::endl;
    oss << generate_builtin_functions() << std::endl;
    
    oss << "} // namespace meld::runtime" << std::endl;
    
    return oss.str();
}

std::string RuntimeLinker::get_runtime_impl() {
    return "// Runtime implementation would go here";
}

std::string RuntimeLinker::generate_memory_management() {
    std::ostringstream oss;
    
    oss << "// Memory management" << std::endl;
    oss << "template<typename T>" << std::endl;
    oss << "using Ref = std::shared_ptr<T>;" << std::endl;
    oss << std::endl;
    oss << "template<typename T>" << std::endl;
    oss << "using WeakRef = std::weak_ptr<T>;" << std::endl;
    oss << std::endl;
    
    return oss.str();
}

std::string RuntimeLinker::generate_type_system() {
    std::ostringstream oss;
    
    oss << "// Type system" << std::endl;
    oss << "class Type {" << std::endl;
    oss << "public:" << std::endl;
    oss << "  virtual ~Type() = default;" << std::endl;
    oss << "  virtual std::string name() const = 0;" << std::endl;
    oss << "};" << std::endl;
    oss << std::endl;
    
    return oss.str();
}

std::string RuntimeLinker::generate_builtin_functions() {
    std::ostringstream oss;
    
    oss << "// Built-in functions" << std::endl;
    oss << "void print(const std::string& s);" << std::endl;
    oss << "void println(const std::string& s);" << std::endl;
    oss << std::endl;
    
    return oss.str();
}

} // namespace meld::compiler
