// rust_backend.cpp — Rust Code Generation Backend (Req 34.2)

#include "meld/compiler/rust_backend.hpp"
#include <sstream>
#include <algorithm>

namespace meld::compiler {

RustBackend::RustBackend(const RustGenerationOptions& options)
    : options_(options) {
    initialize_type_mappings();
}

void RustBackend::initialize_type_mappings() {
    type_mappings_ = {
        {"int",     "i64"},
        {"float",   "f64"},
        {"bool",    "bool"},
        {"string",  "String"},
        {"unit",    "()"},
        {"nil",     "()"},
    };
}

std::string RustBackend::map_type(const std::string& meld_type) const {
    auto it = type_mappings_.find(meld_type);
    if (it != type_mappings_.end()) return it->second;
    return meld_type;  // User-defined types pass through
}

std::string RustBackend::sanitize_rust_identifier(const std::string& name) const {
    std::string result;
    for (char c : name) {
        result += (c == '-') ? '_' : c;  // kebab-case → snake_case
    }
    return result;
}

std::map<std::string, std::string>
RustBackend::generate_rust_files(const ir::Module& module) {
    std::map<std::string, std::string> files;
    files["src/lib.rs"] = generate_rust_module(module);
    if (options_.generate_cargo_toml) {
        files["Cargo.toml"] = generate_cargo_toml(module);
    }
    return files;
}

std::string RustBackend::generate_cargo_toml(const ir::Module& module) {
    std::ostringstream oss;
    oss << "[package]\n"
        << "name = \"" << sanitize_rust_identifier(module.name) << "\"\n"
        << "version = \"0.1.0\"\n"
        << "edition = \"" << options_.edition << "\"\n";
    if (options_.use_anyhow) {
        oss << "\n[dependencies]\nanyhow = \"1\"\n";
    }
    return oss.str();
}

std::string RustBackend::generate_rust_module(const ir::Module& module) {
    std::ostringstream oss;
    oss << "// Generated by Meld compiler — Rust backend\n"
        << "// Source: " << module.name << "\n\n";

    if (options_.use_anyhow) {
        oss << "use anyhow::Result;\n\n";
    }

    // Generate functions
    for (const auto& func : module.functions) {
        oss << generate_rust_function(*func) << "\n";
    }

    return oss.str();
}

std::string RustBackend::generate_rust_function(const ir::Function& func) {
    std::ostringstream oss;
    std::string name = sanitize_rust_identifier(func.name);

    oss << "fn " << name << "(";

    // Parameters
    for (size_t i = 0; i < func.parameters.size(); ++i) {
        if (i > 0) oss << ", ";
        oss << sanitize_rust_identifier(func.parameters[i]->name)
            << ": " << map_type("int");
    }

    oss << ")";

    // Return type
    if (func.return_value) {
        std::string rt = map_type(func.return_value->name);
        if (rt != "()") oss << " -> " << rt;
    }

    oss << " {\n";

    // Body
    for (const auto& bb : func.basic_blocks) {
        if (bb->label != "entry" && !bb->label.empty()) {
            oss << "    // " << bb->label << ":\n";
        }
        for (const auto& inst : bb->instructions) {
            oss << "    " << generate_rust_instruction(*inst) << "\n";
        }
    }

    oss << "}\n";
    return oss.str();
}

std::string RustBackend::generate_rust_instruction(const ir::Instruction& inst) {
    std::ostringstream oss;
    switch (inst.opcode) {
        case ir::Opcode::Return:
            if (!inst.operands.empty()) {
                oss << "return " << inst.operands[0]->name << ";";
            } else {
                oss << "return;";
            }
            break;
        case ir::Opcode::ConstInt:
            if (inst.result) {
                oss << "let " << inst.result->name << ": i64 = "
                    << std::get<int64_t>(inst.constant_value) << ";";
            }
            break;
        case ir::Opcode::ConstString:
            if (inst.result) {
                oss << "let " << inst.result->name << " = String::from(\""
                    << std::get<std::string>(inst.constant_value) << "\");";
            }
            break;
        case ir::Opcode::ConstBool:
            if (inst.result) {
                oss << "let " << inst.result->name << ": bool = "
                    << (std::get<bool>(inst.constant_value) ? "true" : "false") << ";";
            }
            break;
        case ir::Opcode::Add:
            if (inst.result && inst.operands.size() >= 2) {
                oss << "let " << inst.result->name << " = "
                    << inst.operands[0]->name << " + " << inst.operands[1]->name << ";";
            }
            break;
        case ir::Opcode::Sub:
            if (inst.result && inst.operands.size() >= 2) {
                oss << "let " << inst.result->name << " = "
                    << inst.operands[0]->name << " - " << inst.operands[1]->name << ";";
            }
            break;
        case ir::Opcode::Call:
            if (inst.result && !inst.operands.empty()) {
                oss << "let " << inst.result->name << " = "
                    << sanitize_rust_identifier(inst.operands[0]->name) << "(";
                for (size_t i = 1; i < inst.operands.size(); ++i) {
                    if (i > 1) oss << ", ";
                    oss << inst.operands[i]->name;
                }
                oss << ");";
            }
            break;
        case ir::Opcode::IntrinsicRetain:
        case ir::Opcode::IntrinsicRelease:
            // Rust has its own ownership — ARC instructions are no-ops
            oss << "// ARC: " << inst.to_string();
            break;
        default:
            oss << "// TODO: " << inst.to_string();
            break;
    }
    return oss.str();
}

} // namespace meld::compiler
