#pragma once

#include <string>
#include <vector>
#include <filesystem>

namespace meld {
namespace history {

/**
 * Validation result
 */
struct ValidationResult {
    bool isValid;
    std::vector<std::string> violations;
    std::vector<std::string> warnings;
    
    ValidationResult() : isValid(true) {}
    
    void addViolation(const std::string& violation) {
        violations.push_back(violation);
        isValid = false;
    }
    
    void addWarning(const std::string& warning) {
        warnings.push_back(warning);
    }
};

/**
 * Validates that source files don't contain inline history
 */
class SourceValidator {
public:
    SourceValidator() = default;
    
    // Validate a single source file
    ValidationResult validateFile(const std::filesystem::path& filePath);
    
    // Validate all source files in a directory
    ValidationResult validateDirectory(const std::filesystem::path& dirPath);
    
    // Check if a line contains inline history markers
    bool containsInlineHistory(const std::string& line);
    
    // Check if a line contains generation comments
    bool containsGenerationComment(const std::string& line);
    
    // Check if a line contains conversation markers
    bool containsConversationMarker(const std::string& line);
    
    // Get forbidden patterns
    std::vector<std::string> getForbiddenPatterns();
    
private:
    // Patterns that indicate inline history
    std::vector<std::string> forbiddenPatterns_ = {
        "// AI Generated:",
        "// Generated by:",
        "// Conversation:",
        "// User:",
        "// Assistant:",
        "// Version:",
        "// Previous version:",
        "// Refinement:",
        "// AI Iteration:",
        "/* AI Generated",
        "/* Generated by",
        "/* Conversation",
    };
    
    // Helper methods
    bool matchesPattern(const std::string& line, const std::string& pattern);
    std::string trim(const std::string& str);
};

} // namespace history
} // namespace meld
