#pragma once

#include "meld/kernel/primitives.hpp"
#include "meld/parser/ast.hpp"
#include <string>
#include <memory>
#include <vector>
#include <map>
#include <expected>
#include <optional>
#include <chrono>

namespace meld::macro {

// ============================================================================
// PROVENANCE PRESERVATION FOR MACROS
// Task 9.4: Add provenance preservation for macros
// Requirements: 6.5, 12.5
// ============================================================================

// Code origin types
enum class CodeOrigin {
    Human,              // Written by human developer
    AIGenerated,        // Generated by AI model
    MacroExpanded,      // Generated by macro expansion
    Derived,            // Derived from other code (e.g., trait derivation)
    Compiler,           // Generated by compiler
    Unknown             // Origin unknown
};

// AI model information
struct AIModelInfo {
    std::string model_name;         // e.g., "GPT-4", "Claude"
    std::string version;            // Model version
    float confidence;               // Confidence score (0.0 - 1.0)
    std::string prompt;             // Original prompt (optional)
    
    AIModelInfo(std::string name, std::string ver, float conf, std::string p = "")
        : model_name(std::move(name))
        , version(std::move(ver))
        , confidence(conf)
        , prompt(std::move(p)) {}
};

// Macro expansion information
struct MacroExpansionInfo {
    std::string macro_name;         // Name of the macro
    std::vector<std::string> args;  // Macro arguments
    size_t expansion_depth;         // Nesting depth of expansion
    std::string source_location;    // Where macro was invoked
    
    MacroExpansionInfo(std::string name, std::vector<std::string> a, size_t depth, std::string loc)
        : macro_name(std::move(name))
        , args(std::move(a))
        , expansion_depth(depth)
        , source_location(std::move(loc)) {}
};

// Derivation information
struct DerivationInfo {
    std::string trait_name;         // Name of derived trait
    std::string source_type;        // Type being derived for
    std::vector<std::string> fields; // Fields used in derivation
    
    DerivationInfo(std::string trait, std::string type, std::vector<std::string> f)
        : trait_name(std::move(trait))
        , source_type(std::move(type))
        , fields(std::move(f)) {}
};

// Provenance metadata
// Tracks the origin and history of code
struct ProvenanceMetadata {
    CodeOrigin origin;                              // Primary origin
    std::optional<AIModelInfo> ai_info;            // AI generation info
    std::optional<MacroExpansionInfo> macro_info;  // Macro expansion info
    std::optional<DerivationInfo> derive_info;     // Derivation info
    
    std::string author;                             // Author (human or AI)
    std::chrono::system_clock::time_point timestamp; // When code was created
    std::vector<std::string> tags;                  // Additional tags
    std::map<std::string, std::string> metadata;    // Custom metadata
    
    // Parent provenance (for tracking transformation chains)
    std::shared_ptr<ProvenanceMetadata> parent;
    
    ProvenanceMetadata(CodeOrigin orig)
        : origin(orig)
        , timestamp(std::chrono::system_clock::now()) {}
};

// Provenance tracker
// Manages provenance information for AST nodes
class ProvenanceTracker {
public:
    // Associate provenance with an AST node
    void set_provenance(const kernel::Value& ast_node, std::shared_ptr<ProvenanceMetadata> provenance);
    
    // Get provenance for an AST node
    std::shared_ptr<ProvenanceMetadata> get_provenance(const kernel::Value& ast_node) const;
    
    // Check if AST node has provenance
    bool has_provenance(const kernel::Value& ast_node) const;
    
    // Create provenance for human-written code
    static std::shared_ptr<ProvenanceMetadata> create_human_provenance(
        const std::string& author
    );
    
    // Create provenance for AI-generated code
    static std::shared_ptr<ProvenanceMetadata> create_ai_provenance(
        const AIModelInfo& ai_info,
        std::shared_ptr<ProvenanceMetadata> parent = nullptr
    );
    
    // Create provenance for macro-expanded code
    static std::shared_ptr<ProvenanceMetadata> create_macro_provenance(
        const MacroExpansionInfo& macro_info,
        std::shared_ptr<ProvenanceMetadata> parent = nullptr
    );
    
    // Create provenance for derived code
    static std::shared_ptr<ProvenanceMetadata> create_derived_provenance(
        const DerivationInfo& derive_info,
        std::shared_ptr<ProvenanceMetadata> parent = nullptr
    );
    
    // Merge provenance from multiple sources
    static std::shared_ptr<ProvenanceMetadata> merge_provenance(
        const std::vector<std::shared_ptr<ProvenanceMetadata>>& provenances
    );
    
    // Clear all provenance data
    void clear();
    
private:
    // Map from AST node ID to provenance
    std::map<size_t, std::shared_ptr<ProvenanceMetadata>> provenance_map_;
    
    // Generate unique ID for AST node
    size_t get_node_id(const kernel::Value& ast_node) const;
};

// Provenance-aware macro expander
// Extends MacroExpander to preserve provenance through expansion
class ProvenanceAwareMacroExpander {
public:
    ProvenanceAwareMacroExpander(ProvenanceTracker& tracker)
        : tracker_(tracker) {}
    
    // Expand macro while preserving provenance
    std::expected<kernel::Value, std::string> 
    expand_with_provenance(const kernel::Value& ast_node,
                          const std::string& macro_name,
                          const std::vector<std::string>& args);
    
    // Derive trait while preserving provenance
    std::expected<kernel::Value, std::string> 
    derive_with_provenance(const kernel::Value& ast_node,
                          const std::string& trait_name,
                          const std::string& type_name);
    
    // Apply attribute while preserving provenance
    std::expected<kernel::Value, std::string> 
    apply_attribute_with_provenance(const kernel::Value& ast_node,
                                   const std::string& attribute_name);
    
    // Get provenance tracker
    ProvenanceTracker& tracker() { return tracker_; }
    const ProvenanceTracker& tracker() const { return tracker_; }
    
private:
    ProvenanceTracker& tracker_;
};

// Provenance query interface
// Query and analyze provenance information
class ProvenanceQuery {
public:
    ProvenanceQuery(const ProvenanceTracker& tracker)
        : tracker_(tracker) {}
    
    // Find all AI-generated code
    std::vector<kernel::Value> find_ai_generated() const;
    
    // Find all macro-expanded code
    std::vector<kernel::Value> find_macro_expanded() const;
    
    // Find all derived code
    std::vector<kernel::Value> find_derived() const;
    
    // Find code by author
    std::vector<kernel::Value> find_by_author(const std::string& author) const;
    
    // Find code by AI model
    std::vector<kernel::Value> find_by_ai_model(const std::string& model_name) const;
    
    // Find code by macro
    std::vector<kernel::Value> find_by_macro(const std::string& macro_name) const;
    
    // Get provenance chain (from root to current)
    std::vector<std::shared_ptr<ProvenanceMetadata>> 
    get_provenance_chain(const kernel::Value& ast_node) const;
    
    // Calculate confidence score for code
    float calculate_confidence(const kernel::Value& ast_node) const;
    
    // Check if code is trustworthy
    bool is_trustworthy(const kernel::Value& ast_node, float threshold = 0.8f) const;
    
private:
    const ProvenanceTracker& tracker_;
};

// Provenance serialization
// Serialize and deserialize provenance information
class ProvenanceSerialization {
public:
    // Serialize provenance to JSON
    static std::string to_json(const ProvenanceMetadata& provenance);
    
    // Deserialize provenance from JSON
    static std::expected<ProvenanceMetadata, std::string> 
    from_json(const std::string& json);
    
    // Serialize provenance to binary format
    static std::vector<uint8_t> to_binary(const ProvenanceMetadata& provenance);
    
    // Deserialize provenance from binary format
    static std::expected<ProvenanceMetadata, std::string> 
    from_binary(const std::vector<uint8_t>& data);
    
    // Export provenance to human-readable format
    static std::string to_readable(const ProvenanceMetadata& provenance);
};

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

// Convert CodeOrigin to string
std::string code_origin_to_string(CodeOrigin origin);

// Parse CodeOrigin from string
std::expected<CodeOrigin, std::string> parse_code_origin(const std::string& str);

// Create a provenance chain visualization
std::string visualize_provenance_chain(
    const std::vector<std::shared_ptr<ProvenanceMetadata>>& chain
);

// Validate provenance metadata
std::expected<void, std::string> validate_provenance(const ProvenanceMetadata& provenance);

// Copy provenance from one node to another
void copy_provenance(const kernel::Value& source,
                    const kernel::Value& target,
                    ProvenanceTracker& tracker);

// Merge provenance when combining multiple nodes
std::shared_ptr<ProvenanceMetadata> merge_node_provenance(
    const std::vector<kernel::Value>& nodes,
    const ProvenanceTracker& tracker
);

} // namespace meld::macro
